написал функцию, которая преобразует имена пользователей в массив
js-tasks-ru/jsbasic-20240919_ilya4060 pull request #10
Opened 2024-09-30 18:10 UTC by ilya-dan

2024-09-30 18:11 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-10-01 04:26 UTC, koalex requested changes
Исправить замечание в **3-1**

2024-10-01 04:26 UTC, koalex commented on 3-module/1-task/index.js
> +  let names = [];
Суть этой задачи - закрепление метода [map](https://learn.javascript.ru/array-methods#map)
Перепишите пожалуйста используя [map](https://learn.javascript.ru/array-methods#map)

2024-10-01 15:14 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-10-01 15:15 UTC, koalex approved these changes
Отлично!

2024-10-01 15:16 UTC, merged